# Ejercicios (cont)

In [1]:
import numpy as np
from dominance import IDSDS, IDWDS
from nasheq import nash
from fictplay import FP
import pareto
import matplotlib.pyplot as plt

## 2.3 Equilibrios de Nash y árboles de juego

In [2]:
A_PA = np.array(['a1', 'a2'])
A_PB = np.array(['b1', 'b2'])
R_PA = np.array([[2, 1], [3, 2]])
R_PB = np.array([[3, 1], [2, 2]])
G_2_3 = { 'PA' : (R_PA, A_PA), 'PB' : (R_PB, A_PB) }

In [3]:
nash(G_2_3)

[array(['a2', 'b2'], dtype='<U2')]

In [4]:
FP(G_2_3, niter = 100000)

{'PA': array([2.99964004e-05, 9.99970004e-01]),
 'PB': array([5.99946005e-05, 9.99940005e-01])}

<p>FP encuentra $(a_2, b_2) = ((0,1), (0,1))$

<p>Arboles del juego con los valores obtenidos con MaxN
<img src="MaxN_2_3.png" alt="MaxN" width="500" height="600">

<p>En el árbol B -> A la estrategia conjunta es $(a2, b2)$ que coincide con NE en estrategias puras.
<p>En el árbol A -> B las estrategias $(a2, b2)$ y $(a1,b1)$ son equivalentes para MaxN en la raíz dado que el valor para A es 2 en ambos casos.
<p>Se observa que tanto para A como para B el valor de jugar segundo es mayor o igual.

<p>Arboles del juego con los valores obtenidos con ExpectiMaxN
<img src="ExpectiMaxN_2_3.png" alt="ExpectiMaxN" width="500" height="600">

<p>Podemos ver que se cumple que el valor de MaxN para el jugador de la raíz es menor o igual que el de la estrategia $\left(\frac{1}{2}, \frac{1}{2}\right)$ del oponente: $2 \leq 2.5$.

## 2.4 Arboles de juego: MaxN, Expectimax, equilibrios de Nash

<p>Arboles del juego con los valores obtenidos con MaxN
<img src="MaxN_2_4.png" alt="MaxN" width="500" height="600">

<p>Arboles del juego con los valores obtenidos con ExpectiMaxN
<img src="ExpectiMaxN_2_4.png" alt="ExpectiMaxN" width="500" height="600">

In [5]:
A_A = np.array(['a1', 'a2'])
A_B = np.array(['b1', 'b2'])
A_C = np.array(['c1', 'c2'])

In [6]:
R_A_a1 = np.array([[1, 2], [2, 0]])
R_B_a1 = np.array([[3, 0], [0, 1]])
R_C_a1 = np.array([[1, 3], [2, 2]])

In [7]:
G_2_4_a1 = { 'B' : (R_B_a1, A_B), 'C' : (R_C_a1, A_C) }

In [8]:
nash(G_2_4_a1)

[]

In [9]:
FP(G_2_4_a1, niter = 100000)

{'B': array([0.50372955, 0.49627045]), 'C': array([0.24980752, 0.75019248])}

In [10]:
print('NE -> B: ({:.3f}, {:.3f}) C: ({:.3f}, {:.3f})'.format(1/2, 1/2, 1/4, 3/4)) 

NE -> B: (0.500, 0.500) C: (0.250, 0.750)


<p>Equilibrios de Nash cuando $A$ juega $a_1$
\begin{align*}
\pi_B &= \bigg( \frac{1}{2}, \frac{1}{2}  \bigg)    &
\pi_C &= \bigg( \frac{1}{4}, \frac{3}{4}  \bigg)    
\end{align*}

In [11]:
NE_B_a1 = np.array([1/2, 1/2])
NE_C_a1 = np.array([1/4, 3/4])

<p>Valor para $A$

In [12]:
V_A_a1 = np.sum(np.matmul(R_A_a1, NE_C_a1) * NE_B_a1)
V_A_a1

1.125

<p>Valor para $B$

In [13]:
V_B_a1 = np.sum(np.matmul(R_B_a1, NE_C_a1) * NE_B_a1)
V_B_a1

0.75

<p>Valor para $C$

In [14]:
V_C_a1 = np.sum(np.matmul(R_C_a1, NE_B_a1) * NE_C_a1)
V_C_a1

2.0

In [15]:
V_a1 = np.array([V_A_a1, V_B_a1, V_C_a1])
V_a1

array([1.125, 0.75 , 2.   ])

In [16]:
R_A_a2 = np.array([[2, 0], [1, 2]])
R_B_a2 = np.array([[0, 1], [2, 0]])
R_C_a2 = np.array([[3, 1], [2, 3]])

In [17]:
G_2_4_a2 = { 'B' : (R_B_a2, A_B), 'C' : (R_C_a2, A_C) }

In [18]:
nash(G_2_4_a2)

[]

In [19]:
FP(G_2_4_a2, niter = 100000)

{'B': array([0.66770987, 0.33229013]), 'C': array([0.33369997, 0.66630003])}

In [20]:
print('NE -> B: ({:.3f}, {:.3f}) C: ({:.3f}, {:.3f})'.format(2/3, 1/3, 1/3, 2/3)) 

NE -> B: (0.667, 0.333) C: (0.333, 0.667)


<p>Equilibrios de Nash cuando $A$ juega $a_2$
\begin{align*}
\pi_B &= \bigg( \frac{2}{3}, \frac{1}{3}  \bigg)    &
\pi_C &= \bigg( \frac{1}{3}, \frac{2}{3}  \bigg)    
\end{align*}

In [21]:
NE_B_a2 = np.array([2/3, 1/3])
NE_C_a2 = np.array([1/3, 2/3])

<p>Valor para $A$

In [22]:
V_A_a2 = np.sum(np.matmul(R_A_a2, NE_C_a2) * NE_B_a2)
V_A_a2

0.9999999999999999

<p>Valor para $B$

In [23]:
V_B_a2 = np.sum(np.matmul(R_B_a2, NE_C_a2) * NE_B_a2)
V_B_a2

0.6666666666666666

<p>Valor para $C$

In [24]:
V_C_a2 = np.sum(np.matmul(R_C_a2, NE_B_a2) * NE_C_a2)
V_C_a2

2.333333333333333

In [25]:
V_a2 = np.array([V_A_a2, V_B_a2, V_C_a2])
V_a2

array([1.        , 0.66666667, 2.33333333])

<p>Valor para $A$ en el nodo raíz del árbol MaxNash

In [26]:
V, a = (V_a1, 'a1') if V_a1[0] >= V_a2[0] else (V_a2, 'a2')
V, a

(array([1.125, 0.75 , 2.   ]), 'a1')